# Generated by Django 5.0.6 on 2024-08-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre_page_accueil', models.CharField(default='Titre par défaut', max_length=255)),
                ('titre', models.CharField(default='Titre par défaut', max_length=255)),
                ('lien', models.CharField(default='https://exemple.com', max_length=255)),
                ('date_publication', models.DateTimeField(help_text='Date au format jour mois année, heure:minute:seconde', verbose_name="Date d'exportation")),
                ('nom_auteur', models.CharField(default='Auteur inconnu', max_length=255)),
                ('description_article', models.TextField(default='Description par défaut')),
                ('statut_image', models.CharField(max_length=255)),
                ('actualite', models.CharField(max_length=255)),
                ('date_exportation', models.DateTimeField(help_text='Date au format jour mois année, heure:minute:seconde', verbose_name="Date d'exportation")),
                ('categorie', models.CharField(default='Catégorie par défaut', max_length=255)),
                ('ordre_actualite', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Article',
                'db_table': 'articles',
            },
        ),
    ]
