# Generated by Django 5.0.6 on 2024-09-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppScraping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_scraping', models.BooleanField(default=False)),
            ],
        ),
    ]
