# Generated by Django 5.0.6 on 2024-09-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppScraping', '0002_scrapingstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapingstatus',
            name='is_scraping',
        ),
        migrations.AddField(
            model_name='scrapingstatus',
            name='status',
            field=models.CharField(default='pending', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrapingstatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
