# Generated by Django 5.0.6 on 2024-09-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppScraping', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='lien',
            field=models.CharField(default='https://exemple.com', max_length=500),
        ),
    ]
